import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import MaintenanceBanner from "@/components/layout/MaintenanceBanner";
import { Toaster } from "@/components/ui/sonner";
import { LanguageProvider } from "@/lib/language-provider";

export const metadata: Metadata = {
  title: "AJP",
  description: "Generated by saniya farzin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LanguageProvider>
        <Toaster
          richColors
          closeButton
          position="top-right"
          toastOptions={{
            className: "rounded-lg shadow-md",
          }}
        />
        <MaintenanceBanner />
        <Navbar />
        {children}
        <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
