import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import MaintenanceBanner from "@/components/layout/MaintenanceBanner";



export const metadata: Metadata = {
  title: "AJP",
  description: "Generated by saniya farzin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MaintenanceBanner />
        <Navbar /> 
        {children} 
        <Footer /> 
      </body>
    </html>
  );
}
